//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_System_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string account { get; set; }
        public string pwd { get; set; }
        public long id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string mail { get; set; }
        public string socialnum { get; set; }
        public long tax { get; set; }
        public long pension { get; set; }
        public long medical { get; set; }
        public string phone { get; set; }
        public Nullable<long> hourlyrate { get; set; }
        public Nullable<long> salary { get; set; }
        public Nullable<decimal> commissionedrate { get; set; }
        public long hourlimit { get; set; }
    }
}
