//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_System_Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class payrollEntities : DbContext
    {
        public payrollEntities()
            : base("name=payrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<employee> employee { get; set; }
        public DbSet<perference> perference { get; set; }
        public DbSet<purchaseorder> purchaseorder { get; set; }
        public DbSet<record> record { get; set; }
        public DbSet<timecard> timecard { get; set; }
        public DbSet<vacation> vacation { get; set; }
        public DbSet<waitdelete> waitdelete { get; set; }
    }
}
