//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_System_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public long pid { get; set; }
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public int amount { get; set; }
        public string status { get; set; }
    }
}
