//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll_System_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class timecard
    {
        public long tid { get; set; }
        public long id { get; set; }
        public System.DateTime begin { get; set; }
        public System.DateTime end { get; set; }
        public Nullable<System.DateTime> subtime { get; set; }
        public long mon { get; set; }
        public long tue { get; set; }
        public long wed { get; set; }
        public long thu { get; set; }
        public long fri { get; set; }
        public long time { get; set; }
        public int chargenum { get; set; }
        public string status { get; set; }
    }
}
